/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2a3d7ce8-4d59-4895-aba0-bf4aefc3717c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kdSUSoyyt",
    "aws_user_pools_web_client_id": "7669145vutseovimr5qra0r34t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://sfajnozrgvg6jknai3ggxmgabm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
